name = "inderes"
compatibility_date = "2025-09-30"

# Cloudflare Pages: static output from Next.js export
pages_build_output_dir = "out"
[vars]
NEXT_ON_PAGES = "1"
NEXT_PUBLIC_ANSWERS_DATA_URL = "https://pub-143cbf8a3b5c4841983236dc7b36dab8.r2.dev/data.json"
